unets:
  unet1: # BASE
    dim: 32
    num_resnet_blocks: 2
    dim_mults: [1,2,4]
    max_text_len: 1
    layer_attns: False 
    layer_cross_attns: [False, False, True]
    cond_images_channels: 1
  unet2: # TSR
    dim: 32
    num_resnet_blocks: 2
    dim_mults: [1,2,4]
    max_text_len: 1
    layer_attns: False 
    layer_cross_attns: [False, False, True]
    memory_efficient: True
    cond_images_channels: 1
  unet3: # TSR
    dim: 32
    num_resnet_blocks: 2
    dim_mults: [1,2,4]
    max_text_len: 1
    layer_attns: False 
    layer_cross_attns: [False, False, True]
    memory_efficient: True
    cond_images_channels: 1
  unet4: # SSR
    dim: 32
    num_resnet_blocks: 2
    dim_mults: [1,2,4]
    max_text_len: 1
    layer_attns: False 
    layer_cross_attns: False
    cond_images_channels: 1
    attend_at_middle: False

imagen:
  condition_on_text: True
  image_sizes: [64, 64, 64, 128]  # resolutions in the cascade: 56x56 -> 56x56 -> 56x56 -> 112x112
  text_embed_dim: 1
  channels: 1
  elucidated: True
  num_sample_steps: [32, 32, 32, 64]
  random_crop_sizes: [null, null, null, 64]
  temporal_downsample_factor: [4, 2, 1, 1] # FPS in the cascade: 8fps -> 16fps -> 32fps -> 32fps
  sigma_min: 0.002
  sigma_max: 80
  sigma_data: 0.25
  rho: 7
  P_mean: -1.2
  P_std: 1.2
  S_churn: [40, 80, 160, 160] # Determined empirically as working values
  S_tmin: 0.05
  S_tmax: 50
  S_noise: 1.003

trainer:
  split_batches: False
  lr: 5e-4
  dl_tuple_output_keywords_names: ['images', 'cond_images', 'text_embeds']

dataset:
  data_path: "/home/data/datasets/ukbb_partial/twelve_slice"
  deactivate_cache: False
  time_res: 32 # IMPORTANT CHANGE IN 1SCM: 8fps instead of 32fps
  slice_res: 12
  res: 128 # resolution
  fps: 32 # frames per second
  duration: 1 #seconds
  grayscale: False

dataloader: # This is adapted when launching the training script
  batch_size: 8
  num_workers: 8

wandb:
  project: "MRIDiffusion"
  entity: "niklas-bubeck"

checkpoint:
  path: "./outputs/diffusion"
  batch_size: 4
  cond_scale: 5.
  save_every_x_it: 1000

